common:
  model_dim: 512
  rope_theta: 1000.0

pre_model:
  max_seqlen: 128
  mhsa_layers: 8
  mhsa_heads: 4
  attn_dim: 256
  mhca_heads: 4
  mhca_attn_dim: 256
  ffn_common_dim: 1024

post_model:
  max_seqlen: 32
  mhsa_layers: 4
  mhsa_heads: 4
  attn_dim: 256
  ffn_common_dim: 1024
