train:
  log_with_wandb: true
  project_name: "PhonoP2C"
  run_name: "V1.0-Base"
  notes: "First Release"
  checkpoint_dir: "./checkpoints/v1_0-base"
  histogram_interval: 10000
  val_interval: 5000
  save_interval: 1