epochs: 10
batchsize: 3072
optimizer: "adamw"    # "adamw" or "ademamix"
learning_rate: 4e-4
weight_decay: 1e-3
warmup_steps: 10000
gradient_clip_val: 1.0
compile_model: true
compile_mode: 'default'

# Loss function.
loss_type: "focal" # "ce" or "focal"
# label_smoothing_epsilon: 0.1
focal_loss_gamma: 1.0
focal_loss_alpha: 0.5

# validation
ece_bins: 15
ece_top_k: 5

# Beam search sentence-accuracy metric (top-K sentence accuracy).
beam_width: 3
beam_search_max_samples: 256

# Task type is Train.
task_type: "train"
