seed: 'no'
set_seed: false
num_workers: 4
keep_in_memory: true
tf32_enabled: true
mixed_precision: 'bf16'
ao_acceleration: 'float8'
optim_8bit: true
optim_paged: false
gradient_checkpointing: true
device: 'cuda'
expandable_segments_enabled: true

# torchrun / single-node DDP
distributed_backend: 'nccl'
distributed_timeout_minutes: 60
